# Generated by Django 2.2.4 on 2020-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
